server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id:  payment_routh  #payment_routh      #路由的id，没有固定的规则但要求唯一，建议配合服务名
          #uri:  http://localhost:8001             #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service       #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**             #断言，路径匹配十五进行路由
            - After=2020-08-27T21:54:37.485+08:00[Asia/Shanghai]


        - id: payment_routh2  #payment_routh2      #路由的id，没有固定的规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001             #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
              - Path=/payment/lb/**              #断言，路径匹配十五进行路由


eureka:
  instance:
    hostname: cloud-gateway-service

  client:
    #表示将自己注册进eurekaServer 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版

