server:
  port: 9002  #9001占用

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.138.128:1111  #linux下nginx的1111端口，做集群
      #  server-addr: localhost:8848 #配置nacos地址，windows版本

management:
  endpoints:
    web:
      exposure:
        include: '*'