server:
  port: 3344

spring:
  application:
    name: cloud-config-center  #注册进eureka服务器的微服务名称
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/ZKY-2020/springcloud-config-1.git  #Github上面的git仓库名称
          #搜索目录
          search-paths:
            - springcloud-config-1
       #读取分支
      label: master
   #rabbitmq相关配置 15672是web管理界面端口，5672是mq访问的端口
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest





eureka:
  client:
    #表示将自己注册进eurekaServer 默认true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版


#rabbitmq相关配置，暴漏bus刷新配置的端口
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'