server:
  port: 8004   #8004表示注册到zookeeper服务器的支付服务提供者端口号

spring:
  application:
    name: cloud-payment-service
    #服务别名，注册到zookeeper到注册中心名称
  cloud:
    zookeeper:
      connect-string: 192.168.138.128:2181




  #datasource:
   # type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    #driver-class-name: com.mysql.cj.jdbc.Driver          #myql驱动包
    #url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    #username: root
    #password: 123456

#mybatis:
 # mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.atguigu.springcloud.entities        #所有entities实体类所在包

